HospitalManagement_POC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/urls.py
from django.urls import path
from .views import *
app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    # Doctor related urls
    path('doctorslist/', DoctorsView, name='doctorslist'),
    path('adddoctor/', AddDoctor, name='adddoctor'),
    path('updatedoctor/<int:pk>/', UpdateDoctor.as_view(), name='updatedoctor'),
    path('deletedoctor/<int:pk>/', DeleteDoctor.as_view(), name='deletedoctor'),
    # nurse related urls
    path('nurseslist/', NursesView, name='nurseslist'),
    path('addnurse/', AddNurse, name='addnurse'),
    path('updatenurse/<int:pk>/', UpdateNurse.as_view(), name='updatenurse'),
    path('deletenurse/<int:pk>/', DeleteNurse.as_view(), name='deletenurse'),
    # patient related urls
    path('patientslist/', PatientsView, name='patientslist'),
    path('addpatient/', AddPatient, name='addpatient'),
    path('updatepatient/<int:pk>/', UpdatePatient.as_view(), name='updatepatient'),
    path('deletepatient/<int:pk>/', DeletePatient.as_view(), name='deletepatient'),
    path('patientdetail/<int:pk>/', PatientDetail, name='patientdetail'),
    # appointment related urls
    path('appointmentslist/', AppointmentsView, name='appointmentslist'),
    path('addappointment/', AddAppointment, name='addappointment'),
    path('updateappointment/<int:pk>/', UpdateAppointment.as_view(), name='updateappointment'),
    path('deleteappointment/<int:pk>/', DeleteAppointment.as_view(), name='deleteappointment'),
    # prescription related urls
    path('prescriptionview/<int:pk>', PrescriptionsView, name='prescriptionview'),
    path('addprescription/', AddPrescription, name='addprescription'),
    # medicine related urls
    path('medicineslist/', MedicinesView, name='medicineslist'),
    path('addmedicine/', AddMedicine, name='addmedicine'),
    path('updatemedicine/<int:pk>/', UpdateMedicine.as_view(), name='updatemedicine'),
    path('deletemedicine/<int:pk>/', DeleteMedicine.as_view(), name='deletemedicine'),
    # note related urls
    path('notesview/<int:pk>/', NotesView, name='notesview'),
    path('addnote/', AddNote, name='addnote'),
    path('updatenote/<int:pk>/', UpdateNote.as_view(), name='updatenote'),
    path('deletenote/<int:pk>/', DeleteNote.as_view(), name='deletenote'),
    # procedure related urls
    path('procedureslist/', ProceduresView, name='procedureslist'),
    path('addprocedure/', AddProcedure, name='addprocedure'),
    path('updateprocedure/<int:pk>/', UpdateProcedure.as_view(), name='updateprocedure'),
    path('deleteprocedure/<int:pk>/', DeleteProcedure.as_view(), name='deleteprocedure'),
]

core/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import *


# Models
class Doctor(models.Model):
    FirstName = models.CharField(max_length=256)
    LastName = models.CharField(max_length=256)
    PhoneNumber = PhoneNumberField(region='GB')
    Address = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.FirstName} {self.LastName}'

    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctors'


class Nurse(models.Model):
    FirstName = models.CharField(max_length=256)
    LastName = models.CharField(max_length=256)
    PhoneNumber = PhoneNumberField(region='GB')
    Address = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.FirstName} {self.LastName}'

    class Meta:
        verbose_name = 'Nurse'
        verbose_name_plural = 'Nurses'


class Patient(models.Model):
    FirstName = models.CharField(max_length=256)
    LastName = models.CharField(max_length=256)
    NHSNumber = models.CharField(max_length=256)
    PhoneNumber = PhoneNumberField(region='GB')
    Address = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.FirstName} {self.LastName}'

    def get_absolute_url(self):
        return reverse('core:patient_detail', args=[str(self.id)])


    class Meta:
        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'


class Appointment(models.Model):
    Time = models.DateTimeField()
    Doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    Patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.Time} {self.Doctor} {self.Patient}'

    class Meta:
        verbose_name = 'Appointment'
        verbose_name_plural = 'Appointments'


class Medicine(models.Model):
    Code = models.CharField(max_length=128)
    Name = models.CharField(max_length=256)
    Brand = models.CharField(max_length=256)
    Description = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.Code} {self.Name}'

    class Meta:
        verbose_name = 'Medicine'
        verbose_name_plural = 'Medicines'


class Prescription(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    Patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)
    Appointment = models.ForeignKey(Appointment, on_delete=models.SET_NULL, null=True)
    Medicine = models.ForeignKey(Medicine, on_delete=models.SET_NULL, null=True)
    Date = models.DateField()
    Dose = models.CharField(max_length=5)

    def __str__(self):
        return f'{self.Date} {self.Dose}'

    class Meta:
        verbose_name = 'Prescription'
        verbose_name_plural = 'Prescriptions'


class Note(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    Patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)
    Note = models.TextField(max_length=5000)

    def __str__(self):
        return f'{self.Doctor} {self.Patient} {self.Note}'

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Notes'


class Procedure(models.Model):
    Name = models.CharField(max_length=512)
    Doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    Nurse = models.ForeignKey(Nurse, on_delete=models.SET_NULL, null=True)
    Patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)
    Date = models.DateField()
    ProcedureID = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.Name} {self.Date} {self.ProcedureID}'

    class Meta:
        verbose_name = 'Procedure'
        verbose_name_plural = 'Procedures'

core/forms.py
from django.forms import ModelForm, DateTimeInput, DateInput
from .models import *


class DoctorForm(ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'


class NurseForm(ModelForm):
    class Meta:
        model = Nurse
        fields = '__all__'


class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'


class MedicineForm(ModelForm):
    class Meta:
        model = Medicine
        fields = '__all__'


class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'
        widgets = {
            'Time': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%d %H:%M')
        }


class PrescriptionForm(ModelForm):
    class Meta:
        model = Prescription
        fields = '__all__'
        widgets = {
            'Date': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
        }


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'


class ProcedureForm(ModelForm):
    class Meta:
        model = Procedure
        fields = '__all__'
        widgets = {
            'Date': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
        }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import *
from .forms import *


# Create your views here.
def home(request):
    return render(request, 'core/index.html')


# Doctor related Views
def DoctorsView(request):
    obj = Doctor.objects.all()
    return render(request, 'core/doctors.html', {'obj': obj, })


def AddDoctor(request):
    title = "Add Doctor"
    if request.method == 'POST':
        form = DoctorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:doctorslist')
    else:
        form = DoctorForm()
    context = {
        'form': form,
        'title': title
    }
    return render(request, 'core/add-edit.html', context)


class UpdateDoctor(UpdateView):
    form_class = DoctorForm
    model = Doctor
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:doctorslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Doctor'
        context['title'] = title
        return context


class DeleteDoctor(DeleteView):
    model = Doctor
    success_url = reverse_lazy('core:doctorslist')


# Nurse related Views
def NursesView(request):
    obj = Nurse.objects.all()
    return render(request, 'core/nurse.html', {'obj': obj, })


def AddNurse(request):
    if request.method == 'POST':
        form = NurseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:nurseslist')
    else:
        form = NurseForm()
    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Nurse"})


class UpdateNurse(UpdateView):
    form_class = PatientForm
    model = Patient
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:nurseslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Nurse'
        context['title'] = title
        return context


class DeleteNurse(DeleteView):
    model = Nurse
    success_url = reverse_lazy('core:nurseslist')


# Patient related View
def PatientsView(request):
    obj = Patient.objects.all()
    return render(request, 'core/patient.html', {'obj': obj, })


def AddPatient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:patientslist')
    else:
        form = PatientForm()
    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Patient"})


class UpdatePatient(UpdateView):
    form_class = PatientForm
    model = Patient
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:patientslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Patient'
        context['title'] = title
        return context


class DeletePatient(DeleteView):
    model = Patient
    success_url = reverse_lazy('core:patientslist')


def PatientDetail(request, pk):
    patient = get_object_or_404(Patient, id=pk)
    prescriptions = Prescription.objects.filter(Patient=patient)
    notes = Note.objects.filter(Patient=patient)

    context = {
        'patient': patient,
        'prescription': prescriptions,
        'note': notes,
    }

    return render(request, 'core/patient_detail.html', context)


# Appointment related views
def AppointmentsView(request):
    obj = Appointment.objects.all()
    return render(request, 'core/appointments.html', {'obj': obj})


def AddAppointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:appointmentslist')
    else:
        form = AppointmentForm()
    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Appointment"})


class UpdateAppointment(UpdateView):
    form_class = AppointmentForm
    model = Appointment
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:appointmentslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Appointment'
        context['title'] = title
        return context


class DeleteAppointment(DeleteView):
    model = Appointment
    success_url = reverse_lazy('core:appointmentslist')


# prescription related views
def PrescriptionsView(request, pk):
    obj = Prescription.objects.filter(Patient_id=pk)


def AddPrescription(request):
    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:patientslist')
    else:
        form = PrescriptionForm()

    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Precsription"})


# medicine related views
def MedicinesView(request):
    obj = Medicine.objects.all()
    return render(request, 'core/medicine.html', {'obj': obj})


def AddMedicine(request):
    if request.method == 'POST':
        form = MedicineForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:medicineslist')
    else:
        form = MedicineForm()
    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Medicine"})


class UpdateMedicine(UpdateView):
    form_class = MedicineForm
    model = Medicine
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:medicineslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Medicine'
        context['title'] = title
        return context


class DeleteMedicine(DeleteView):
    model = Medicine
    success_url = reverse_lazy('core:medicineslist')


# notes related views
def NotesView(request, pk):
    obj = Note.objects.filter(Patient_id=pk)


def AddNote(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:patientslist')
    else:
        form = NoteForm()

    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Note"})


class UpdateNote(UpdateView):
    form_class = MedicineForm
    model = Medicine
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:patientslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Note'
        context['title'] = title
        return context


class DeleteNote(DeleteView):
    model = Note
    success_url = reverse_lazy('core:patientslist')


# Procedure related views
def ProceduresView(request):
    obj = Procedure.objects.all()
    return render(request, 'core/procedure.html', {'obj': obj, 'title': "Procedures"})


def AddProcedure(request):
    if request.method == 'POST':
        form = ProcedureForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:procedureslist')
    else:
        form = ProcedureForm()

    return render(request, 'core/add-edit.html', {'form': form, 'title': "Add Procedure"})


class UpdateProcedure(UpdateView):
    form_class = ProcedureForm
    model = Procedure
    template_name = 'core/add-edit.html'
    success_url = reverse_lazy('core:procedureslist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Update Procedure'
        context['title'] = title
        return context


class DeleteProcedure(DeleteView):
    model = Procedure
    success_url = reverse_lazy('core:procedureslist')

templates/core/appointments.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Appointments List</h4>
                            <a href="{% url 'core:addappointment' %}" class="btn btn-info float-right">Add Appointment</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>Time</th>
                                            <th>Doctor</th>
                                            <th>Patient</th>
                                            <th>Update</th>
                                            <th>Delete</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                        <tr>
                                            <td>{{ obj.Time }}</td>
                                            <td>{{ obj.Doctor }}</td>
                                            <td>{{ obj.Patient }}</td>
                                            <td><a href="{% url 'core:updateappointment' obj.pk %}">Update</a> </td>
                                            <td><a href="{% url 'core:deleteappointment' obj.pk %}">Delete</a> </td>
                                        </tr>
                                        {% endfor %}

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/core/doctors.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Doctors List</h4>
                            <a href="{% url 'core:adddoctor' %}" class="btn btn-info float-right">Add Doctor</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Phone Number</th>
                                            <th>Address</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                        <tr>
                                            <td>{{ obj.FirstName }}</td>
                                            <td>{{ obj.LastName }}</td>
                                            <td>{{ obj.PhoneNumber }}</td>
                                            <td>{{ obj.Address }}</td>
                                            <td><a href="{% url 'core:updatedoctor' obj.pk %}">Update</a> </td>
                                            <td><a href="{% url 'core:deletedoctor' obj.pk %}">Delete</a> </td>

                                        </tr>
                                        {% endfor %}


                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/core/medicine.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Medicines List</h4>
                            <a href="{% url 'core:addmedicine' %}" class="btn btn-info float-right">Add Medicine</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>Code</th>
                                            <th>Name</th>
                                            <th>Brand</th>
                                            <th>Description</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                        <tr>
                                            <td>{{ obj.Code }}</td>
                                            <td>{{ obj.Name}}</td>
                                            <td>{{ obj.Brand }}</td>
                                            <td>{{ obj.Description }}</td>
                                            <td><a href="{% url 'core:updatemedicine' obj.pk %}">Update</a> </td>
                                            <td><a href="{% url 'core:deletemedicine' obj.pk %}">Delete</a> </td>
                                        </tr>
                                        {% endfor %}


                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/core/nurse.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Nurses List</h4>
                            <a href="{% url 'core:addnurse' %}" class="btn btn-info float-right">Add Nurse</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Phone Number</th>
                                            <th>Address</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                            <tr>
                                                <td>{{ obj.FirstName }}</td>
                                                <td>{{ obj.LastName }}</td>
                                                <td>{{ obj.PhoneNumber }}</td>
                                                <td>{{ obj.Address }}</td>
                                                <td><a href="{% url 'core:updatenurse' obj.pk %}">Update</a></td>
                                                <td><a href="{% url 'core:deletenurse' obj.pk %}">Delete</a></td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/core/patient.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Patients List</h4>
                            <a href="{% url 'core:addpatient' %}" class="btn btn-info float-right">Add Patient</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>NHS Number</th>
                                            <th>Phone Number</th>
                                            <th>Address</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                            <tr>

                                                <td> <a href="{% url 'core:patientdetail' obj.pk %}">{{ obj.FirstName }}</a></td>
                                                    <td>{{ obj.LastName }}</td>

                                                <td>{{ obj.NHSNumber }}</td>
                                                <td>{{ obj.PhoneNumber }}</td>
                                                <td>{{ obj.Address }}</td>
                                                <td><a href="{% url 'core:updatepatient' obj.pk %}">Update</a></td>
                                                <td><a href="{% url 'core:deletepatient' obj.pk %}">Delete</a></td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/core/procedure.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content-body" style="margin: 5%">
        <section id="configuration">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Procedures List</h4>
                            <a href="{% url 'core:addprocedure' %}" class="btn btn-info float-right">Add Procedure</a>

                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Doctor</th>
                                            <th>Nurse</th>
                                            <th>Patient</th>
                                            <th>Date</th>
                                            <th>Procedure ID</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for obj in obj %}
                                        <tr>
                                            <td>{{ obj.Name }}</td>
                                            <td>{{ obj.Doctor}}</td>
                                            <td>{{ obj.Nurse }}</td>
                                            <td>{{ obj.Patient }}</td>
                                            <td>{{ obj.Date }}</td>
                                            <td>{{ obj.ProcedureID }}</td>
                                            <td><a href="{% url 'core:updateprocedure' obj.pk %}">Update</a> </td>
                                            <td><a href="{% url 'core:deleteprocedure' obj.pk %}">Delete</a> </td>
                                        </tr>
                                        {% endfor %}


                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}