HospitalManagement_POC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/urls.py
from django.urls import path
from .views import *
app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    # Doctor related urls
    path('doctorslist/', DoctorsView, name='doctorslist'),
    path('adddoctor/', AddDoctor, name='adddoctor'),
    path('updatedoctor/<int:pk>/', UpdateDoctor.as_view(), name='updatedoctor'),
    path('deletedoctor/<int:pk>/', DeleteDoctor.as_view(), name='deletedoctor'),
    # nurse related urls
    path('nurseslist/', NursesView, name='nurseslist'),
    path('addnurse/', AddNurse, name='addnurse'),
    path('updatenurse/<int:pk>/', UpdateNurse.as_view(), name='updatenurse'),
    path('deletenurse/<int:pk>/', DeleteNurse.as_view(), name='deletenurse'),
    # patient related urls
    path('patientslist/', PatientsView, name='patientslist'),
    path('addpatient/', AddPatient, name='addpatient'),
    path('updatepatient/<int:pk>/', UpdatePatient.as_view(), name='updatepatient'),
    path('deletepatient/<int:pk>/', DeletePatient.as_view(), name='deletepatient'),
    path('patientdetail/<int:pk>/', PatientDetail, name='patientdetail'),
    # appointment related urls
    path('appointmentslist/', AppointmentsView, name='appointmentslist'),
    path('addappointment/', AddAppointment, name='addappointment'),
    path('updateappointment/<int:pk>/', UpdateAppointment.as_view(), name='updateappointment'),
    path('deleteappointment/<int:pk>/', DeleteAppointment.as_view(), name='deleteappointment'),
    # prescription related urls
    path('prescriptionview/<int:pk>', PrescriptionsView, name='prescriptionview'),
    path('addprescription/', AddPrescription, name='addprescription'),
    # medicine related urls
    path('medicineslist/', MedicinesView, name='medicineslist'),
    path('addmedicine/', AddMedicine, name='addmedicine'),
    path('updatemedicine/<int:pk>/', UpdateMedicine.as_view(), name='updatemedicine'),
    path('deletemedicine/<int:pk>/', DeleteMedicine.as_view(), name='deletemedicine'),
    # note related urls
    path('notesview/<int:pk>/', NotesView, name='notesview'),
    path('addnote/', AddNote, name='addnote'),
    path('updatenote/<int:pk>/', UpdateNote.as_view(), name='updatenote'),
    path('deletenote/<int:pk>/', DeleteNote.as_view(), name='deletenote'),
    # procedure related urls
    path('procedureslist/', ProceduresView, name='procedureslist'),
    path('addprocedure/', AddProcedure, name='addprocedure'),
    path('updateprocedure/<int:pk>/', UpdateProcedure.as_view(), name='updateprocedure'),
    path('deleteprocedure/<int:pk>/', DeleteProcedure.as_view(), name='deleteprocedure'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
   
    <title>ChemoCare</title>

    <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700"
    rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/vendors.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/datatables.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/charts/chartist.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/charts/chartist-plugin-tooltip.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/components.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/css/core/menu/menu-types/horizontal-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/colors/palette-gradient.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/colors/palette-gradient.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/chat-application.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/dashboard-analytics.css' %}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="horizontal-layout horizontal-menu 2-columns  " data-open="hover" data-menu="horizontal-menu"
      data-color="bg-gradient-x-purple-blue" data-col="2-columns">

<!-- BEGIN: Header-->
<!-- fixed-top-->
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item" style="margin-top: 4%"><a class="navbar-brand" href="{% url 'core:home' %}">
                        <h3 class="brand-text">ChemoCare Patient Management System</h3>
                    </a></li>
                    <li class="dropdown nav-item mega-dropdown d-none d-md-block">
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- END: Header-->
{% block content %}

{% endblock %}


<!-- BEGIN: Vendor JS-->
<script src="{% static 'app-assets/vendors/js/vendors.min.js' %}" type="text/javascript"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script type="text/javascript" src="{% static 'app-assets/vendors/js/ui/jquery.sticky.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/datatables.min.js' %}" type="text/javascript"></script>

<script src="{% static 'app-assets/vendors/js/charts/chartist.min.js' %}" type="text/javascript"></script>
<script src="{% static 'app-assets/vendors/js/charts/chartist-plugin-tooltip.min.js' %}"
        type="text/javascript"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{% static 'app-assets/js/core/app-menu.js' %}" type="text/javascript"></script>
<script src="{% static 'app-assets/js/core/app.js' %}" type="text/javascript"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="{% static 'app-assets/js/scripts/pages/dashboard-analytics.js' %}" type="text/javascript"></script>
<!-- END: Page JS-->
    <script src="{% static 'app-assets/js/scripts/tables/datatables/datatable-basic.js' %}" type="text/javascript"></script>

</body>
<!-- END: Body-->

</html>